# Generated by Django 5.2.1 on 2025-05-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(default=1, verbose_name='Contenido2'),
            preserve_default=False,
        ),
    ]
