# Generated by Django 5.2 on 2025-05-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='key',
            field=models.SlugField(default=1, max_length=200, unique=True, verbose_name='NOmbre clave'),
            preserve_default=False,
        ),
    ]
