# Generated by Django 5.2 on 2025-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_social_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='key',
            field=models.SlugField(max_length=200, verbose_name='Nombre clave'),
        ),
    ]
