# Generated by Django 5.2 on 2025-05-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_social_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='key',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nombre clave'),
        ),
    ]
